server:
  #port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: dentista-api
  datasource:
    url: jdbc:postgresql://host/database
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate.format_sql: true
